# Generated by Django 4.2.2 on 2023-07-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_owerName',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='ownerName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
